/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, MeshReflectorMaterial, useTexture } from "@react-three/drei";
import { useControls } from 'leva'

export default function Library(props) {
  const { nodes, materials } = useGLTF("/library.glb");



  return (
    <group {...props} dispose={null}>
        <directionalLight castshadow intensity={0.06}/>
      
      <group position={[0, 0, -1.8]} rotation={Math.Pi}>
        <directionalLight
          castshadow
          name="Area"
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[11.21, 2.13, -18.58]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[3.53, 1.56, 1.56]}
        />
      
        <directionalLight
          name="Area002"
          castShadow
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[11.21, 2.13, -9.57]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[3.53, 1.56, 1.56]}
        />

        <directionalLight
          name="Area004"
          castShadow
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[11.21, 2.13, -0.56]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[3.53, 1.56, 1.56]}
        />
        <directionalLight
          name="Area015"
          castShadow
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[11.21, 8.52, -18.64]}
          rotation={[-Math.PI / 2, 1.21, Math.PI]}
          scale={[4.88, 2.1, 2.1]}
        />
    
        <directionalLight
          name="Area017_1"
          castShadow
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[11.21, 8.52, -9.63]}
          rotation={[-Math.PI / 2, 1.21, Math.PI]}
          scale={[4.88, 2.1, 2.1]}
        />

        <directionalLight
          castShadow
          name="Area019_1"
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[11.21, 8.52, -0.62]}
          rotation={[-Math.PI / 2, 1.21, Math.PI]}
          scale={[4.88, 2.1, 2.1]}
        />
        <directionalLight
          castShadow
          name="Area030"
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[-11.18, 8.52, -18.71]}
          rotation={[-1.57, -1.21, 0]}
          scale={[4.88, 2.1, 2.1]}
        />
   
        <directionalLight
          castShadow
          name="Area032_1"
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[-11.18, 8.52, -9.7]}
          rotation={[-1.57, -1.21, 0]}
          scale={[4.88, 2.1, 2.1]}
        />
 
        <directionalLight
          castShadow
          name="Area034_1"
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[-11.18, 8.52, -0.69]}
          rotation={[-1.57, -1.21, 0]}
          scale={[4.88, 2.1, 2.1]}
        />
        <directionalLight
          castShadow
          name="Area045"
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[-11.13, 2.13, -18.58]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={[3.53, 1.56, 1.56]}
        />

        <directionalLight
          castShadow
          name="Area047_1"
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[-11.13, 2.13, -9.57]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={[3.53, 1.56, 1.56]}
        />
 
        <directionalLight
          castShadow
          name="Area049_1"
          intensity={0.06}
          angle={0.17}
          penumbra={0.15}
          decay={2}
          position={[-11.13, 2.13, -0.56]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={[3.53, 1.56, 1.56]}
        />
      </group>

      <mesh
        name="floor_main"
        castShadow
        receiveShadow
        geometry={nodes.floor_main.geometry}
        // material={materials["Material.001"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <MeshReflectorMaterial
          map={nodes.floor_main.material.map}
          resolution={128}
          blur={[1000, 1000]}
          mixBlur={1}
          mirror={0.4}
        />
      </mesh>

      <mesh
        name="pedestals"
        castShadow
        receiveShadow
        geometry={nodes.pedestals.geometry}
        material={materials.pedestal}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <group
        name="building"
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name="Cube004_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials.walls}
        />
        <mesh
          name="Cube004_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube004_2.geometry}
          material={materials.ceiling}
        />
      </group>
      <group
        name="building001"
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name="Cube012"
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials.walls}
        />
        <mesh
          name="Cube012_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube012_1.geometry}
          material={materials.carpet}
        />
        <mesh
          name="Cube012_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube012_2.geometry}
          material={materials.ceiling}
        />
      </group>
      <mesh
        name="baluster_front001"
        castShadow
        receiveShadow
        geometry={nodes.baluster_front001.geometry}
        material={materials.baluster}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="baluster_front002"
        castShadow
        receiveShadow
        geometry={nodes.baluster_front002.geometry}
        material={materials.baluster}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="SubTool-1-11412745"
        castShadow
        receiveShadow
        geometry={nodes["SubTool-1-11412745"].geometry}
        material={materials["Material.001"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="baluster_front"
        castShadow
        receiveShadow
        geometry={nodes.baluster_front.geometry}
        material={materials.baluster}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="window_frame_bottom"
        castShadow
        receiveShadow
        geometry={nodes.window_frame_bottom.geometry}
        material={materials.Arch}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="SubTool-0-11414000"
        castShadow
        receiveShadow
        geometry={nodes["SubTool-0-11414000"].geometry}
        material={materials["Material.001"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="npg_70_4_base-hires_unwrapped-150k-unwrapped001"
        castShadow
        receiveShadow
        geometry={
          nodes["npg_70_4_base-hires_unwrapped-150k-unwrapped001"].geometry
        }
        material={materials["Material.005"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="middle_pillar"
        castShadow
        receiveShadow
        geometry={nodes.middle_pillar.geometry}
        material={materials.column}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="stand1"
        castShadow
        receiveShadow
        geometry={nodes.stand1.geometry}
        material={materials["Material.005"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="George_Barco_Bust002"
        castShadow
        receiveShadow
        geometry={nodes.George_Barco_Bust002.geometry}
        material={materials["Material.001"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="SubTool-0-11413759"
        castShadow
        receiveShadow
        geometry={nodes["SubTool-0-11413759"].geometry}
        material={materials["Material.001"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="SubTool-0-11415487002"
        castShadow
        receiveShadow
        geometry={nodes["SubTool-0-11415487002"].geometry}
        material={materials["Material.001"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="stand9"
        castShadow
        receiveShadow
        geometry={nodes.stand9.geometry}
        material={materials["Material.005"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Object_0005"
        castShadow
        receiveShadow
        geometry={nodes.Object_0005.geometry}
        material={materials["Material.001"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="stand1001"
        castShadow
        receiveShadow
        geometry={nodes.stand1001.geometry}
        material={materials["Material.005"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="doorframe2"
        castShadow
        receiveShadow
        geometry={nodes.doorframe2.geometry}
        material={materials.doorframe_up}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cube006"
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.Material}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Cube007"
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.Material}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="door_right"
        castShadow
        receiveShadow
        geometry={nodes.door_right.geometry}
        material={materials.door_right}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="columns_top"
        castShadow
        receiveShadow
        geometry={nodes.columns_top.geometry}
        material={materials.pillars_top}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="door_left"
        castShadow
        receiveShadow
        geometry={nodes.door_left.geometry}
        material={materials.door_left}
        position={[0.08, 0, 13.8]}
        rotation={[0, 0, -Math.PI]}
        scale={-1}
      />
      <group
        name="Cube"
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name="Cube_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.baked1}
        />
        <mesh
          name="Cube_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.bookshelf_down}
        />
        <mesh
          name="Cube_3"
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={materials["baked1.001"]}
        />
      </group>
      <group
        name="Cube002"
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name="Cube018"
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          material={materials["baked1.001"]}
        />
        <mesh
          name="Cube018_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube018_1.geometry}
          material={materials["bookshelf_down.001"]}
        />
        <mesh
          name="Cube018_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube018_2.geometry}
          material={materials.baked1}
        />
      </group>
      <group
        name="Cube004"
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name="Cube019"
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials.baked1}
        />
        <mesh
          name="Cube019_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube019_1.geometry}
          material={materials.bookshelf_down}
        />
        <mesh
          name="Cube019_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube019_2.geometry}
          material={materials["baked1.001"]}
        />
      </group>
      <group
        name="Cube005"
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name="Cube020"
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials["baked1.001"]}
        />
        <mesh
          name="Cube020_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials.baked1}
        />
        <mesh
          name="Cube020_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={materials["bookshelf_down.001"]}
        />
      </group>
      <mesh
        name="npg_70_4_bust-hires_unwrapped-150k-unwrapped001"
        castShadow
        receiveShadow
        geometry={
          nodes["npg_70_4_bust-hires_unwrapped-150k-unwrapped001"].geometry
        }
        material={materials["Material.001"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="SubTool-1-11417255002"
        castShadow
        receiveShadow
        geometry={nodes["SubTool-1-11417255002"].geometry}
        material={materials["Material.001"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="doorframe1"
        castShadow
        receiveShadow
        geometry={nodes.doorframe1.geometry}
        material={materials.doorframe}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="doorframe3"
        castShadow
        receiveShadow
        geometry={nodes.doorframe3.geometry}
        material={materials.doorframe_up}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="frame_front"
        castShadow
        receiveShadow
        geometry={nodes.frame_front.geometry}
        material={materials.arc_top}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="carpetL"
        castShadow
        receiveShadow
        geometry={nodes.carpetL.geometry}
        material={materials.carpet}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="carpetR"
        castShadow
        receiveShadow
        geometry={nodes.carpetR.geometry}
        material={materials.carpet}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <group
        name="diez_C002"
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name="diez_C002_1"
          castShadow
          receiveShadow
          geometry={nodes.diez_C002_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="diez_C002_2"
          castShadow
          receiveShadow
          geometry={nodes.diez_C002_2.geometry}
          material={materials.GeneratedMat1}
        />
      </group>
      <mesh
        name="arch_side"
        castShadow
        receiveShadow
        geometry={nodes.arch_side.geometry}
        material={materials.arc_small}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="SubTool-0-11414019"
        castShadow
        receiveShadow
        geometry={nodes["SubTool-0-11414019"].geometry}
        material={materials["Material.001"]}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <group
        name="ceiling_side"
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name="Cylinder014"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014.geometry}
          material={materials.ceiling_small}
        />
        <mesh
          name="Cylinder014_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014_1.geometry}
          material={nodes.Cylinder014_1.material}
        />
        <mesh
          name="Cylinder014_2"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014_2.geometry}
          material={materials.ceiling}
        />
      </group>
    
      <group
        name="floor_top_right001"
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name="Plane001"
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.WoodFlooring056_3K}
        />
        <mesh
          name="Plane001_1"
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={nodes.Plane001_1.material}
        />
      </group>
      <group
        name="floor_top_right002"
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name="Plane002"
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.WoodFlooring056_3K}
        />
        <mesh
          name="Plane002_1"
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={nodes.Plane002_1.material}
        />
      </group>
      <mesh
        name="arch_main"
        castShadow
        receiveShadow
        geometry={nodes.arch_main.geometry}
        material={materials.arc_big}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="ledge"
        castShadow
        receiveShadow
        geometry={nodes.ledge.geometry}
        material={materials.ledge}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="ledge_front"
        castShadow
        receiveShadow
        geometry={nodes.ledge_front.geometry}
        material={materials.ledge}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="JRO_Sample_Orn87"
        castShadow
        receiveShadow
        geometry={nodes.JRO_Sample_Orn87.geometry}
        material={materials.ornaments}
        position={[0.08, 0, 13.8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/library.glb");
